#define ERROR_FUNCT -1
#define USAGE       "usage : ax filename"
#define MISSING_ARG "ax : missing filename"
#define LOAD_MESSAGE    "loading"
#define NOT_OPEN_FILE   "cannot open file"
#define FILE_ERROR  "ax : bad format"
#define NOT_A_TYPE  "ax : not 'A' file type "
#define MSG_UND     "**	underflow error			**"
#define MSG_OVR     "**	overflow error			**"
#define MSG_PC_ERR  "**	program counter out of limits	**"
#define MSG_OUT_MEM "**	segmentation violation		**"
#define ARIT_OVER   "**	aritmetic overflow		**"
#define DIV_BY_ZERO "**	divided by zero			**"
#define MSG_NOT_INST    "**	instruction not implemented	**"
#define MSG_COD_INST    "Code of instruction  :"
#define MSG_INST    "Type of instruction  :"
#define MSG_POI     "Value of bad pointer :"
#define MSG_PC      "Value of PC	:"
#define MSG_SP      "Value of SP	:"
#define MSG_RI      "Instruction	:"
#define CODE_RI     "Instruct. code :"
#define MSG_FL      "Value of FLAG  :"
